name: A Site You Want To Track
favicon: null
layout_spectrum: 0.7604751088656485
typography_spectrum: 0.6602775007486343
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.07164431130513549
purpose:
  - name: awareness
    item: null
    url: null
